import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./assets/globals.css";
import Navbar from "./components/ui/Navbar";
import Background from "./components/ui/Background";

const myLinks = [
  { href: "/", label: "Welcome" },
  { href: "/dashboard/Login", label: "Login" }
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-800 text-slate-100`}>    
        <header>
          <Navbar links={myLinks}/>
        </header>   
        <main>
          {children}
        </main>
        <Background/>
      </body>
    </html>
  );
}
